### ISSUE TITLE
PRIMITIVE_LOOKUP_FAILED error. 

### ISSUE THREAD

**Issue by pmatatias** [lask/toit-hc-sr04#12]
I follow the tutorial from the documentation https://docs.toit.io/tutorials/hardware/ultra/#measuring-by-hand

It successfully works without the package. 

![image](https://github.com/lask/toit-hc-sr04/assets/33835308/727f7e27-f951-429e-934c-9369a6579762)

---

Next I continue the tutorial using this package. and I get this error
```
[jaguar] INFO: program edd37d55-64e5-b4a0-d907-9502899269f6 started

******************************************************************************
Decoding by `jag`, device has version <2.0.0-alpha.130>
******************************************************************************
PRIMITIVE_LOOKUP_FAILED error. 
Failed to find primitive 11:0
  0: rmt-init_                 <sdk>\rmt.toit:563:1
  1: resource-group_           <sdk>\rmt.toit:561:21
  2: run-global-initializer__.<block> <sdk>\core\objects.toit:286:28
  3: run-global-initializer__  <sdk>\core\objects.toit:252:1
  4: Channel                   <sdk>\rmt.toit:275:34
  5: Channel                   <sdk>\rmt.toit:320:15
  6: Driver                    <pkg:toit-hc-sr04>\driver.toit:56:16
  7: main                      hcsr04.toit:36:13
******************************************************************************

[jaguar] ERROR: program edd37d55-64e5-b4a0-d907-9502899269f6 stopped - exit code 1
```

also tried the comment here https://github.com/lask/toit-hc-sr04/issues/9#issuecomment-1426478080 
but still no luck.

any suggestions for this issue?

TIA

**Comment by floitsch** [comment]
We will try to reproduce.

In the meantime, could you tell us which version of the package you are using?
Maybe just upload the package.lock file?

**Comment by pmatatias** [comment]
This is my `package.lock`

```
sdk: ^2.0.0-alpha.91
prefixes:
  hc_sr04: toit-hc-sr04
  telegram: toit-telegram
packages:
  pkg-http:
    url: github.com/toitlang/pkg-http
    name: http
    version: 2.3.4
    hash: 39fe52083b4c745cc37420649a48277b45728fd2
  toit-cert-roots:
    url: github.com/toitware/toit-cert-roots
    name: certificate_roots
    version: 1.6.1
    hash: 55d3be82ed53d8d332338b2de931865cf69fe48b
  toit-hc-sr04:
    url: github.com/lask/toit-hc-sr04
    name: hc_sr04
    version: 2.1.1
    hash: da8389adec9f012999c385b69bc42e26e19b51fa
  toit-telegram:
    url: github.com/floitsch/toit-telegram
    name: telegram
    version: 0.5.2
    hash: 86f963b32a97f3d473d4261c19cb9af3f0354688
    prefixes:
      certificate_roots: toit-cert-roots
      http: pkg-http
```
